language: java
jdk: openjdk8
env:
  global:
    #SONATYPE_USERNAME
    - secure: akAh+eCG+jK8FIDB/boVtgyFtYeNpLoz4PL+4PWYDTlKVt4iquMyky32m5mvSVTZc1NdlS2YHg4FHEyLz5nKUYh+WtBjP6C5PWgpJa752EzLc1NsQq2sqr6Ghxkg09Gzeda4lOkZaU/tbATwwXKGpirjYZVvsjIaJ8sEL7ptao+TdWIkZUuuGcJJ7zqm7168d0pqGmwXaYywoZ6yVq/7XK4a7MpELyipSQTt1a8BIgWBZ+d4NipB/99DjD1Hr0IEbrlvk6d2nYqhIty2bRxx/pdxrgC/mw3LP5k08FpY5IlX7H5JykpLsSjmL8GGao9/ywEvwKYMJRpTk2WuLKwaRtlfWSQ4Y15b1Tb2ydcR/wnrzfW9kV1quspEjf/sB4TrxPlYOwF/9OVs3xYPRFFFFUEOEFm1ILJFZpzLrrEFles8FaoirbOj43Bpug8Rh6ZJ2Bmb0weQZ028yGk8ye/0qbPX6C2XbHYgDyT5Jj6fQ0vzEHnsvGw5NOPZ2AoA42TFivQr7U+Al4NCMXpzF8cG9uMe6KlPw3sC1RZLNJcKG6Djj46v2wvJScH9fqF5PUIFbKsX8Z+ssTnLzJnAtHFWKCMgi+J7OtbgJHhMAEYf+Cohqi+n6dLdWDmCZUOumzXBBtp/GOVa/akgeM04/navk/kSRv9djPRRoU7YDhiBbSE=
    #SONATYPE_PASSWORD
    - secure: YYHA3coDwAeycaXVE26ih+Au0GbxRdjzxDKex0y77mKnLclHWLBysVygj1S/7zVUCLqdvPBhgG4kFhVkHvSTHcDREIPqGg4wcCHdhA/RXO+ZtdGsnUxh9mZVbekbiS/nIw4YvzKkfK2hf78upnybqx9hrB/o/3UyOsyaQxOREZsmFwXbdUUKgXHbgbvurCTNjuIjiQf9K88AcWHSEBbvjKsqD9qkh+toY7k6tnGGTUVVmM07ZB00BcHlabVIijg/6wTLj17e1EtKtT2CJ4Wci/vQ6WL2NThkoLGzzX+RWh1yEQq4kbdeQO+LMf/afosSsKb4lhxLuu/USwRgCoD13ryjs1GT9V41LcXynZ0d6yHTZW6XQ5TTa6ar1YBpUaqNew62jhm0NV3lH8/H6lod84duefibt2lOfQSDavc1wleV3tCQnEOnxyvX9nrx1Vxb/IXYSi+pHLLc0+SXbYhX6UWf1WRuiiJbil/M7oRUXNqHVoLHC516oSK6dU8vff9/uzV0Qx6ExC8JAc2jIQEwO7UMwr1GIWU5LdmPHUM2eYXkib7YlHeLcnyUGSjDbYToeOEcdbqzGYYgoWDuaIK9brWQ1LTXPzZ3gmS0i8E4ms7kjdD4vRzn5Otyc3Ktq6znpEs1bNZhvBJwPQ4DITPgi9hz6m6w6nFX07uH+6sTaIo=

services:
  - docker

before_install:
  - docker pull mysql:5

install: cp ./.travis/maven.settings.xml $HOME/.m2/settings.xml
before_script: docker-compose -f ./.travis/databases.docker-compose.yml up -d
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash -c "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent integration-test verify -Dliquibase.version.qualifier="-${TRAVIS_BRANCH}" -Dbuild.number=${TRAVIS_BUILD_NUMBER} -Dbuild.commit=${TRAVIS_COMMIT}"; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash -c "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent integration-test deploy sonar:sonar -Dsonar.projectKey=liquibase_liquibase -Ddeploy.url=https://oss.sonatype.org/content/repositories/snapshots -Ddeploy.repositoryId=sonatype -Dliquibase.version.qualifier="-${TRAVIS_BRANCH}" -Dbuild.number=${TRAVIS_BUILD_NUMBER} -Dbuild.commit=${TRAVIS_COMMIT}"; fi'
after_script: docker-compose -f ./.travis/databases.docker-compose.yml down

cache:
  directories:
  - "~/.m2"
addons:
  sonarcloud:
    organization: "liquibase-oss"
    token:
      secure: LnotzNSdNvo46OiOwqCpuvG48auUnwdn78T6c2RXk39k9gtK/yBLrrSbnuBqShbYn4llXxHSLkvalfBa8Ck5w6BpMOoTInpsOWverK+0PyVmgJUv9wNIAV/9+CJS7QsBivLUf6STT7ABfbcoUiWSZUJnOS5zIZukySk+/lmMnRW2h5GniRw3N0MFPtu4G+IZ1jqWhlHovjq41JWHEGCs1+jKQPmajQLOu4RKtihEfBAVXBIorjJIXl9TcPQAbTltYPe4oRSLMRQ/Qj3PMpgsSMLRKmzJ/sgzmgzPSdlTDcsnLOjnnp6f/5mt7arZx/k78xJ+CVezr+QIIU4tpaWZqPC7T7mRh9nixQnXhNpg91zibMTb8XUIdJ8fpMlqPeHHUcKzYJ6074e0BM9JEqXSW9hvWtuscoN1nNJFyGocqaeuZ7/sUxa6zEVNRaUZ3kWoZbttkQ5AKAuYS/oVnWmkMGx5AhNqVCynGv78jIyxHSR3n4gla66+lWZqKVb1ySt8qpeHE9Ep8O0Z9EouykTCYDKJiPvwbYns5auAJdqUCuQadGh0wRBJccEDlC0LcPVilQiCrEpMOCNLmYmjVbwKm6ZFMnHfS/xB7TjgSA0CmbkX0lsDIWypwkm+TkHVg6Uw6fEpgNMOBd8W6b7XMGEUfqZcbYfPvJVSN0aeUKoYPN8=
after_success:
  - bash <(curl -s https://codecov.io/bash)
