name: FOSSA License Compliance and Security Check

permissions:
  contents: read
  pull-requests: write
  actions: read
  id-token: write

on:
  repository_dispatch:
    types: [ oss-released-version ]

jobs:
  fossa:
    uses: liquibase/build-logic/.github/workflows/fossa_ai.yml@main
    secrets: inherit
