name: Release Extensions
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Liquibase Version'
        required: true

jobs:
  automated-os-extensions-release:
    uses: liquibase/build-logic/.github/workflows/extension-automated-release.yml@main
    secrets: inherit
    with:
      version: ${{ inputs.version }}

