name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release

permissions:
  contents: read

jobs:
  create_draft_release_release_branch:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Throttle Requests (Release)
        if: github.ref == 'refs/heads/release'
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Delaying for 10 seconds...');
            await new Promise(resolve => setTimeout(resolve, 10000));

      - name: Create Draft Release (Release)
        if: github.ref == 'refs/heads/release'

        # Drafts your next Release notes as Pull Requests are merged into the default branch
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-release.yml # located in .github/ in default branch
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_DRAFTER_TOKEN }}

  create_draft_release_master:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Create Draft Release (Master)
        if: github.ref == 'refs/heads/master'

        # Drafts your next Release notes as Pull Requests are merged into the default branch
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-master.yml # located in .github/ in default branch
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_DRAFTER_TOKEN }}