name: Release Extensions
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Liquibase Version'
        required: true

jobs:
  trigger-release:
    name: "Trigger Releases"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        extension:
          - docker
          - liquibase-bigquery
          - liquibase-cache
          - liquibase-cassandra
          - liquibase-cosmosdb
          - liquibase-db2i
          - liquibase-filechangelog
          - liquibase-nochangeloglock
          - liquibase-hanadb
          - liquibase-hibernate
          - liquibase-maxdb
          - liquibase-modify-column
          - liquibase-mongodb
          - liquibase-mssql
          - liquibase-oracle
          - liquibase-postgresql
          - liquibase-redshift
          - liquibase-sqlfire
          - liquibase-teradata
          - liquibase-vertica
          - liquibase-yugabytedb
    steps:
      - name: Release liquibase/${{ matrix.extension }} v${{ github.event.inputs.version }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            console.log("Sending liquibase-release event to liquibase/${{ matrix.extension }}");

            await github.rest.repos.createDispatchEvent({
               "owner": "liquibase",
               "repo": "${{ matrix.extension }}",
               "event_type": "liquibase-release",
               "client_payload": {
                  "liquibaseVersion": "${{ github.event.inputs.version }}"
                }
             });
